autoload -U colors && colors
PS1="%B%F{034}%n@%m%f%b:%B%F{019}%~ %#%f%b "


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"



alias musique="mpv --no-video --term-osd-bar --no-resume-playback --term-playing-msg='file: ${media-title}' --shuffle --playlist=$HOME/Music/lamusique.txt"
export PATH="/usr/local/opt/openssl@3/bin:$PATH"
export PATH="/usr/local/opt/tcl-tk/bin:$PATH"
alias beep="echo -ne '\007'"
source ~/perl5/perlbrew/etc/bashrc
